In [2]:
import numpy as np
import random

In [6]:
a=np.random.random(1)

In [10]:
np.random.random((3,3))

array([[0.90261117, 0.49853934, 0.99554055],
       [0.09312213, 0.72322283, 0.39008824],
       [0.18849373, 0.75867463, 0.90511532]])

In [12]:
np.random.randint(1,4,(3,3))

array([[3, 1, 2],
       [3, 2, 2],
       [2, 2, 1]])

In [13]:
np.random.randint(1,10,(3,3,3))

array([[[9, 5, 7],
        [3, 7, 8],
        [1, 8, 6]],

       [[2, 7, 9],
        [4, 3, 8],
        [2, 4, 2]],

       [[3, 1, 9],
        [6, 6, 2],
        [2, 9, 2]]])

In [14]:
np.random.seed(10)
np.random.randint(1,10,(3,3,3))

array([[[5, 1, 2],
        [1, 2, 9],
        [1, 9, 7]],

       [[5, 4, 1],
        [5, 7, 9],
        [2, 9, 5]],

       [[2, 4, 7],
        [6, 4, 7],
        [2, 5, 3]]])

In [16]:
np.random.seed(10)
np.random.randint(1,10,(3,3,3))

array([[[5, 1, 2],
        [1, 2, 9],
        [1, 9, 7]],

       [[5, 4, 1],
        [5, 7, 9],
        [2, 9, 5]],

       [[2, 4, 7],
        [6, 4, 7],
        [2, 5, 3]]])

In [17]:
np.random.rand(3)

array([0.05644419, 0.76545582, 0.01178803])

In [18]:
np.random.rand(3,3)

array([[0.61194334, 0.33188226, 0.55964837],
       [0.33549965, 0.41118255, 0.0768555 ],
       [0.85304299, 0.43998746, 0.12195415]])

In [23]:
x=[1,2,3,4,5]
np.random.choice(x)

1