# Numpy function:

In [1]:
import numpy as np

In [2]:
np.arange?

In [3]:
ar_1d=np.arange(1,17)

In [4]:
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [5]:
np.linespace(1,5,4)

AttributeError: module 'numpy' has no attribute 'linespace'

In [8]:
np.linespace(1,5,4)

AttributeError: module 'numpy' has no attribute 'linespace'

In [7]:
np.linespace?

Object `np.linespace` not found.


In [9]:
print(range(1,5))

range(1, 5)


In [10]:
a=range(1,5)
print(a)

range(1, 5)


In [11]:
print(np.arange(1,5))

[1 2 3 4]


In [12]:
import numpy as np 
# the default value of num is 50
print(np.linspace(1,50))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]


In [19]:
import numpy as np 
print(np.linspace(1,5,3))

[1. 3. 5.]


In [20]:
ar_4d=ar_1d.reshape(4,4)

In [21]:
print(ar_4d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [22]:
 print(ar_1d.reshape(2,8))

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [23]:
print(np.shape(ar_4d))

(4, 4)


In [24]:
print(ar_1d.reshape(2,4,2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [30]:
print(np.array([[1,2,3],[2,34,4],[5,6,7]]))

[[ 1  2  3]
 [ 2 34  4]
 [ 5  6  7]]


In [31]:
print(ar_4d.ravel)

<built-in method ravel of numpy.ndarray object at 0x00000193DE28C3F0>


In [32]:
print(ar_4d.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [33]:
print(ar_4d.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [36]:
ar_4d.flatten()

Object `np.flatten` not found.


In [37]:
 ar_1d.transpose()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [40]:
ar=ar_1d.reshape(8,2)

In [41]:
ar.transpose()

array([[ 1,  3,  5,  7,  9, 11, 13, 15],
       [ 2,  4,  6,  8, 10, 12, 14, 16]])

In [46]:
a=np.linspace(1,50)

In [45]:
print(a)

[ 1. 13.]


In [48]:
a=np.linspace(1,50,3)
print(a)

[ 1.  25.5 50. ]
