In [1]:
import numpy as np

In [2]:
arr1=np.arange(1,17).reshape(4,4)
arr2=np.arange(17,33).reshape(4,4)

In [3]:
print(arr1)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [4]:
print(arr1+arr2)

[[18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]]


In [5]:
list1=[1,2,3,4,5]
list2=[5,6,7,8,9,4]
list1+list2

[1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 4]

In [6]:
np.concatenate((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [7]:
np.concatenate((arr1,arr2),axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [8]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [9]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [10]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [11]:
np.split(arr1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [12]:
list1=np.split(arr1,2)

In [13]:
type(list1)

list

In [14]:
print(list1[1])

[[ 9 10 11 12]
 [13 14 15 16]]


In [15]:
type(list1[1])
np.split(list1[1],2,axis=0)

[array([[ 9, 10, 11, 12]]), array([[13, 14, 15, 16]])]

In [16]:
np.split(arr1,2,axis=0)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [22]:
np.split(arr1,2,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [18]:
d1=np.arange(1,13)
print(d1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [19]:
list=np.split(d1,[2,6])

In [20]:
list[1]

array([3, 4, 5, 6])